apiVersion: v2
name: ixo-kyc-server
description: A Helm chart for Kubernetes
type: application
version: 0.0.38
appVersion: v1.0.0-develop.40
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixofoundation/ixo-kyc-server app version from v1.0.0-develop.39 to v1.0.0-develop.40
