apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ixo-matrix-claims-bot.fullname" . }}-config
  labels:
    {{- include "ixo-matrix-claims-bot.labels" . | nindent 4 }}
data:
  production.yaml: |-
    # Where the homeserver's Client-Server API is located. Typically this
    # is where clients would be connecting to in order to send messages.
    homeserverUrl: "http://matrix-synapse.matrix-synapse.svc.cluster.local:8008"
    homeserverName: "testmx.ixo.earth"
    accessToken: "<path:ixo_core/data/matrix#MATRIX_CLAIMS_BOT_ACCESS_TOKEN>"
    graphqlUrl: "https://testnet-blocksync-graphql.ixo.earth/graphql"
    rpcUrl: "https://testnet.ixo.earth/rpc/"

    # Whether or not to autojoin rooms when invited.
    autoJoin: true

    # Location on disk for where to store various bot information.
    dataPath: "./ixo-claims-bot-storage"

    encryption: true

    # Recovery key for restoring encryption keys from server backup
    # Format: Base58 with spaces (e.g., "EsTc LW2K ...")
    recoveryKey: "<path:ixo_core/data/matrix#MATRIX_CLAIM_BOT_RECOVERY_KEY>"

    # The blockchain API endpoint to query for DID documents
    blockchainRpcUri: "https://testnet.ixo.earth/rpc/"

    # The blocksync API endpoint to query for users DID documents using graphql
    blocksyncUri: "https://testnet-blocksync-graphql.ixo.earth/"

    # REST API config
    restApi:
      # Set to true to enable the REST API
      enabled: true
      # Port to listen on for the REST API, default is 8080
      port: 8083
      # express trust proxy config for if you are using a reverse proxy
      trustProxy: 1