apiVersion: v2
name: memory-engine-graphiti
description: A Helm chart for Kubernetes
type: application
version: 0.0.21
appVersion: main-223cf6b
dependencies:
- name: matrix-bridge-api
  version: 0.0.1
  repository: file://./charts/matrix-bridge-api
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/memory-engine-graphiti app version from main-d65990d to main-223cf6b
