apiVersion: v2
name: memory-engine-graphiti
description: A Helm chart for Kubernetes
type: application
version: 0.0.22
appVersion: main-ffecbd7
dependencies:
- name: matrix-bridge-api
  version: 0.0.2
  repository: file://./charts/matrix-bridge-api
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/memory-engine-graphiti app version from main-223cf6b to v1.1.0-develop.2
