apiVersion: v2
name: ixo-matrix-appservice-rooms
description: A Helm chart for Kubernetes
type: application
version: 0.0.29
appVersion: v0.8.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixofoundation/ixo-matrix-appservice-rooms app version from v0.8.0 to v0.8.1
