apiVersion: v2
name: ixo-supamoto-onboarding-server
description: A Helm chart for Kubernetes
type: application
version: 0.0.63
appVersion: v1.1.0-develop.37
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-supamoto-onboarding-server app version from v1.1.0-develop.36 to v1.1.0-develop.37
