apiVersion: v2
name: ixo-matrix-appservice-rooms
description: A Helm chart for Kubernetes
type: application
version: 0.0.17
appVersion: v0.7.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixofoundation/ixo-matrix-appservice-rooms app version from v0.6.0 to v0.7.0
