apiVersion: v2
name: ixo-matrix-appservice-rooms
description: A Helm chart for Kubernetes
type: application
version: 0.0.15
appVersion: v0.5.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixofoundation/ixo-matrix-appservice-rooms app version from v0.5.1 to v0.5.2
