apiVersion: v2
name: domain-creator-oracle
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 1.1.79
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update
