apiVersion: v2
name: api-server
description: Firecrawler API Server component
type: application
version: 0.0.2
appVersion: develop-17aba47
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update api-server app version from latest to develop-17aba47
