apiVersion: v2
name: ixo-matrix-bids-bot
description: A Helm chart for Kubernetes
type: application
version: 0.0.7
appVersion: v1.0.0-develop.7
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-matrix-bids-bot app version from v1.0.0-develop.6 to v1.0.0-develop.7
