apiVersion: v2
name: ixo-matrix-bids-bot
description: A Helm chart for Kubernetes
type: application
version: 0.0.11
appVersion: v1.4.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-matrix-bids-bot app version from v1.4.0 to v1.4.1
