apiVersion: v2
name: ixo-matrix-claims-bot
description: A Helm chart for Kubernetes
type: application
version: 0.0.13
appVersion: v1.3.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-matrix-claims-bot app version from v1.2.2 to v1.3.0
