apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ixo-firecrawler.fullname" . }}-playwright
  labels:
    {{- include "ixo-firecrawler.labels" . | nindent 4 }}
    app.kubernetes.io/component: playwright-service
spec:
  replicas: {{ index .Values "playwright-service" "replicaCount" | default .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ixo-firecrawler.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: playwright-service
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ixo-firecrawler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: playwright-service
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ixo-firecrawler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: playwright-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ index .Values "playwright-service" "image" "repository" }}:{{ index .Values "playwright-service" "image" "tag" | default (index .Subcharts "playwright-service").Chart.AppVersion }}"
          imagePullPolicy: {{ index .Values "playwright-service" "image" "pullPolicy" }}
          env:
            - name: FIRECRAWL_API_URL
              value: {{ include "ixo-firecrawler.firecrawlApiURL" . | quote }}
            {{- with (index .Values "playwright-service" "env") }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: playwright
              containerPort: {{ .Values.service.playwrightPort }}
              protocol: TCP
          resources:
            {{- toYaml (index .Values "playwright-service" "resources") | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
