apiVersion: v2
name: ixo-matrix-supamoto-claims-bot
description: A Helm chart for Kubernetes
type: application
version: 0.0.12
appVersion: v1.1.9
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-matrix-supamoto-claims-bot app version from v1.1.8 to v1.1.9
