apiVersion: v2
name: ixo-matrix-state-bot
description: A Helm chart for Kubernetes
type: application
version: 0.1.5
appVersion: v0.1.0-develop.4
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixofoundation/ixo-matrix-state-bot app version from v0.1.0-develop.3 to v0.1.0-develop.4
