apiVersion: v2
name: companion
description: A Helm chart for Kubernetes
type: application
version: 0.0.5
appVersion: 1.2.12
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/companion-app app version from 1.2.8 to 1.2.12
