apiVersion: v2
name: ixo-matrix-state-bot
description: A Helm chart for Kubernetes
type: application
version: 0.1.6
appVersion: v0.2.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixofoundation/ixo-matrix-state-bot app version from v0.2.1 to v0.2.2
