apiVersion: v2
name: ixo-supamoto-onboarding-server
description: A Helm chart for Kubernetes
type: application
version: 0.0.24
appVersion: v1.1.8
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-supamoto-onboarding-server app version from v1.1.7 to v1.1.8
