apiVersion: v2
name: ixo-supamoto-onboarding-server
description: A Helm chart for Kubernetes
type: application
version: 0.0.51
appVersion: v1.1.35
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-supamoto-onboarding-server app version from v1.1.34 to v1.1.35
