apiVersion: v2
name: website-bot-oracle
description: A Helm chart for Kubernetes
type: application
version: 0.0.5
appVersion: 1.0.46
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/website-bot-oracle-app app version from 1.0.45 to 1.0.46
