apiVersion: v2
name: domain-indexer
description: A Helm chart for Kubernetes
type: application
version: 0.0.10
appVersion: v1.1.0-develop.8
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/domain-indexer app version from v1.1.0-develop.7 to v1.1.0-develop.8
