apiVersion: v2
name: domain-indexer
description: A Helm chart for Kubernetes
type: application
version: 0.0.17
appVersion: v1.10.0-develop.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/domain-indexer app version from v1.1.0-develop.14 to v1.10.0-develop.1
