apiVersion: v2
name: ecs-oracle
description: A Helm chart for Kubernetes
type: application
version: 0.0.14
appVersion: 2.0.4
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ecs-oracle-app app version from 2.0.3 to 2.0.4
