apiVersion: v2
name: ecs-oracle
description: A Helm chart for Kubernetes
type: application
version: 0.0.18
appVersion: 2.1.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ecs-oracle-app app version from 2.1.0 to 2.1.1
