apiVersion: v2
name: ecs-oracle
description: A Helm chart for Kubernetes
type: application
version: 0.0.11
appVersion: 1.3.6
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ecs-oracle-app app version from 1.3.5 to 1.3.6
