apiVersion: v2
name: minerva
description: A Helm chart for Kubernetes
type: application
version: 0.0.25
appVersion: 1.1.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/minerva-app app version from 1.0.7 to 1.1.0
