apiVersion: v2
name: minerva
description: A Helm chart for Kubernetes
type: application
version: 0.0.23
appVersion: 1.0.6
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/minerva-app app version from 1.0.5 to 1.0.6
