apiVersion: v2
name: ixo-matrix-claims-bot
description: A Helm chart for Kubernetes
type: application
version: 0.0.15
appVersion: v1.0.0-develop.14
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-matrix-claims-bot app version from v1.0.0-develop.13 to v1.0.0-develop.14
