apiVersion: v2
name: ixo-ussd-supamoto
description: A Helm chart for Kubernetes
type: application
version: 0.0.10
appVersion: v1.0.0-dev.6
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update emerging-eco/ixo-ussd-supamoto app version from v1.0.0-dev.5 to v1.0.0-dev.6
