apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ixo-matrix-whatsapp.fullname" . }}-data
  labels:
    {{- include "ixo-matrix-whatsapp.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- .Values.persistentVolume.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  {{- if .Values.persistentVolume.storageClass }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  {{- end }}
