apiVersion: v2
name: ixo-matrix-supamoto-bot
description: A Helm chart for Kubernetes
type: application
version: 0.0.57
appVersion: v1.1.13
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-matrix-supamoto-bot app version from v1.1.12 to v1.1.13
