apiVersion: v2
name: ixo-matrix-supamoto-bot
description: A Helm chart for Kubernetes
type: application
version: 0.0.69
appVersion: v1.1.19-dev.7
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/ixo-matrix-supamoto-bot app version from v1.1.19-dev.6 to v1.1.19-dev.7
