apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ixo-matrix-state-bot.fullname" . }}-config
  labels:
    {{- include "ixo-matrix-state-bot.labels" . | nindent 4 }}
data:
  production.yaml: |-
    # Where the homeserver's Client-Server API is located. Typically this
    # is where clients would be connecting to in order to send messages.
    homeserverUrl: "http://matrix-synapse.matrix-synapse.svc.cluster.local:8008"

    # An access token for the bot to use. Learn how to get an access token
    # at https://t2bot.io/docs/access_tokens
    accessToken: "<path:ixo_core/data/matrix#MATRIX_STATE_BOT_TOKEN>"

    # Whether or not to autojoin rooms when invited.
    autoJoin: true

    # Location on disk for where to store various bot information.
    dataPath: "storage"

    # Set to false to disable encryption support. Encrypted data will be
    # stored under dataPath.
    encryption: true

    # Recovery key for restoring encryption keys from server backup
    # Format: Base58 with spaces (e.g., "EsTc LW2K ...")
    recoveryKey: "<path:ixo_core/data/matrix#MATRIX_STATE_BOT_RECOVERY_KEY>"

    # The blocksync API endpoint to query for users DID documents using graphql
    blocksyncUri: "https://devnet-blocksync-graphql.ixo.earth/"

    # Network (devnet or testnet or mainnet)
    network: "devnet"

    # REST API config
    restApi:
      # Set to true to enable the REST API
      enabled: true
      # Port to listen on for the REST API, default is 8080
      port: 8080
      # express trust proxy config for if you are using a reverse proxy
      trustProxy: 1