apiVersion: v2
name: companion
description: A Helm chart for Kubernetes
type: application
version: 0.0.22
appVersion: 1.1.77
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/companion-app app version from 1.1.76 to 1.1.77
