apiVersion: v2
name: companion
description: A Helm chart for Kubernetes
type: application
version: 0.0.5
appVersion: 0.2.10
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/companion-app app version from 0.2.9 to 0.2.10
