apiVersion: v2
name: companion
description: A Helm chart for Kubernetes
type: application
version: 0.0.7
appVersion: 1.0.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/companion-app app version from 0.2.11 to 1.0.0
