apiVersion: v2
name: companion
description: A Helm chart for Kubernetes
type: application
version: 0.0.13
appVersion: 1.1.4
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/companion-app app version from 1.1.3 to 1.1.4
