apiVersion: v2
name: companion
description: A Helm chart for Kubernetes
type: application
version: 0.0.11
appVersion: 1.1.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/companion-app app version from 1.1.1 to 1.1.2
