apiVersion: v2
name: companion
description: A Helm chart for Kubernetes
type: application
version: 0.0.21
appVersion: 1.1.76
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/companion-app app version from 1.1.74 to 1.1.76
