apiVersion: v2
name: domain-creator-oracle
description: A Helm chart for Kubernetes
type: application
version: 0.0.6
appVersion: 1.2.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/domain-creator-oracle-app app version from 1.2.0 to 1.2.1
