apiVersion: v2
name: domain-creator-oracle
description: A Helm chart for Kubernetes
type: application
version: 0.0.5
appVersion: 1.2.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/domain-creator-oracle-app app version from 1.0.43 to 1.2.0
