apiVersion: v2
name: domain-indexer
description: A Helm chart for Kubernetes
type: application
version: 0.0.6
appVersion: v1.4.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/domain-indexer app version from v1.3.0 to v1.4.0
