apiVersion: v2
name: website-bot-oracle
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 1.0.45
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update
