apiVersion: v2
name: ixo-ussd-supamoto
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: v1.0.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update
