apiVersion: v1
kind: Service
metadata:
  name: {{ include "ixo-supamoto-onboarding-server.fullname" . }}
  labels:
    {{- include "ixo-supamoto-onboarding-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ixo-supamoto-onboarding-server.selectorLabels" . | nindent 4 }}
