apiVersion: v2
name: companion
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 1.1.73
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update
