apiVersion: v2
name: ixo-blocksync
description: A Helm chart for Kubernetes
type: application
version: 2.1.41
appVersion: v2.5.0-develop.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixofoundation/ixo-blocksync app version from v2.4.0-ws2 to v2.5.0-develop.1
